version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: projeto_final_modulo01
    ports:
      - 5438:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=education
